export default {
  STATUS_CODES: {
    ACCESS_DENIED: 401,
    BAD_REQUEST: 400,
    OK: 200,
    INTERNAL_ERROR: 500,
    NOT_FOUND: 404,
    CONFLICT: 409,
    FILENOTFOUND: 415,
  },

  IMAGE_URL: "http://vr-physio.hktechlabs.com/public/admin/img/",
  VERIFY_EMAIL: "Verify Email",
  VERIFY_CURRENT_EMAIL: "Verify current email",
  VERIFY_NEW_EMAIL: "Verify new email.",
  FORGOT_PASSWORD: "Forgot Password",
  FEEDBACK_CREATED: "Feedback Created",
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  UPCOMING: "UPCOMING",
  PAST: "PAST",
  COMPLETED: "COMPLETED",
  ACCEPTED: "ACCEPTED",
  CANCELLED: "CANCELLED",
  ORGANIZATION: "ORGANIZATION",
  DOCTOR: "DOCTOR",
  USER: "USER",
  PATIENT: "PATIENT",
  ADMIN: "ADMIN",
  STANDALONE_DOCTOR: "STANDALONE_DOCTOR",
  PENDING: "PENDING",
  IN_PROGRESS: "IN-PROGRESS",
  COMPLETE: "COMPLETE",
  FAILED: "FAILED",
  CREATED: "CREATED",
  PAID: "PAID",
  REFUNDED: "REFUNDED",
  SUCCESS: "SUCCESS",

  SUCCESS_MESSAGES: {
    SET_ROLE: "Role must be set.",
    USER_REGISTERED: "User registered successfully.",
    PREROUTINE_SAVE: "PreRoutine saved successfully.",
    APPOINTMENT_BOOK: "Appointment booked successfully.",
    APPOINTMENT_DELETE: "Appointment deleted successfully.",
    APPOINTMENT_CANCEL: "Appointment canceled successfully.",
    APPOINTMENT_COMPLETED: "Appointment complete successfully.",
    APPOINTMENT_FETCHED: "Appointment data fetched successfully.",
    GAMES_FETCHED: "Game data fetched successfully.",
    GAME_ADD: "Game Saved successfully.",
    APPOINTMENT_RESCHEDULED: "Appointment rescheduled successfully.",
    APPOINTMENT_FETCH: "Appointments fetched successfully.",
    BODY_PARTS_FETCH: "Body parts fetched successfully.",
    BODY_PARTS_MOVEMENT_FETCH: "Movement fetch successfully.",
    ROUTINE_SAVE: "Routine saved successfully.",
    PREROUTINE_FETCHED: "PreRoutine fetch successfully.",
    ROUTINE_FETCHED: "Routine fetch successfully.",
    PATIENT_DETAILS_INSERTED: "Patient details inserted successfully.",
    PATIENT_CREATE: "Patient created successfully.",
    PATIENT_FETCHED: "Patient details fetched successfully",
    PATIENT_DETAILS_UPDATE: "Patient details update successfully.",
    DOCTOR_DETAILS_INSERTED: "Doctor details inserted successfully.",
    DOCTOR_DETAILS: "Doctor details fetched successfully.",
    DOCTOR_DELETE: "Doctor details delete successfully.",
    DOCTOR_DETAILS_UPDATE: "Doctor details update successfully.",
    DOCTOR_ACTIVE: "Doctor active successfully.",
    DOCTOR_INACTIVE: "Doctor inactive successfully.",
    ORGANIZATION_DETAILS_INSERTED:
      "Organization details inserted successfully.",
    ORGANIZATION_UPDATE: "Organization details updated successfully.",
    MENU_DETAIL_FETCHED: "Menu details fetched successfully.",
    DASHBOARD_DATA_FETCHED: "Dashboard data fetched successfully.",
    OTP_SENT_LOGIN: "OTP sent successfully for login.",
    OTP_SENT_SIGNUP: "OTP sent successfully for signup.",
    PREFERENCES_UPDATED: "Notification days saved successfully.",
    OTP_SEND: "OTP sent successfully to email.",
    EMAIL_VERIFIED: "Email verified successfully.",
    OTP_VERIFIED: "OTP verified successfully.",
    PROFILE_UPDATE: "Profile updated successfully.",
    PASSWORD_UPDATE: "Password updated successfully.",
    REQUEST_SENT_TO_ADMIN: "Request sent successfully to admin.",
    SUCCESS_UPDATE: "Updated successfully.",
    USER_UPDATED: "User updated successfully.",
    USER_DELETED: "User deleted successfully.",
    USER_FETCH: "Users fetched successfully.",
    USER_REGISTRATION: "User registered successfully.",
    USER_LOGIN: "User logged in successfully.",
    USER_LOGOUT: "User logged out successfully.",
    PASSWORD_UPDATED: "Password updated successfully.",
    PRODUCT_DELETED: "Product deleted successfully.",
    FEEDBACK_CREATED: "Feedback submitted successfully.",
    FEEDBACKS_FETCHED: "Feedbacks retrieved successfully.",
    PERSONAL_ADDED: "Personal details added successfully.",
    NOTIFICATIONS_SENT: "Notifications sent successfully.",
    EXERCISE_fOUND: "Exercise found successfully.",
    EXERCISE_SAVE: "Exercise Save successfully.",
    SESSION_SAVE: "Session Save successfully.",
    SESSION_FETCHED: "Session fetched successfully.",
    SESSION_PENDING: "No pending Session found.",
    PAYMENT_FETCHED: "Payment fetched successfully.",
    PAYMENT_SUCCESS: "Payment successfull.",
    ORDER_CREATE: "Order create successfully.",
    FILE_UPLOAD: "File upload successfully.",
    DEVICE_ADDED: "Device added successfully.",
    DEVICE_FETCH: "Device fetch sucessfully.",
    DEVICE_UPDATED: "Device Updated Successfully",
  },

  ERROR_MESSAGES: {
    UNAUTHORIZED: "Unauthorized Token.",
    SESSION_NOT_FOUND: "Session not found.",
    PREROUTINE_NOT_FOUND: "PreRoutine  Not Found.",
    ACCOUNT_NOT_ACTIVE: "Your account has not been activated by admin.",
    EMAIL_EXIST: "Email Exist",
    SET_ROLE: "Role must be set",
    ROUTINE_NOT_FOUND: "Routine Not Found",
    ALL_FIELD_REQUIRED: "All fields are required.",
    INVALID_CREDENTIALS: "Invalid credentials.",
    INVALID_INPUT: "Invalid input.",
    INVALID_ID: "User ID is required.",
    GAMES_NOT_FOUND: "Games not found.",
    SERVER_ERROR: "An internal server error occurred. Please retry later.",
    INVALID_OTP: "Invalid OTP.",
    INVALID_TOKEN: "Invalid or expired token.",
    NO_TOKEN_PROVIDED: "No token provided. Access denied.",
    EMAIL_EXISTS: "Email already exists.",
    EMAIL_NOT_EXIST: "Invalid email provided.",
    CONTACT_NUMBER_NOT_FOUND: "Contact number does not exist.",
    PASSWORD_INVALID: "Invalid email or password.",
    PHONE_NOT_FOUND: "Phone number does not exist.",
    PASSWORD_NOT_MATCH: "Current password does not match.",
    USER_NOT_FOUND: "User does not exist.",
    PATIENT_NOT_FOUND: "Patient not found.",
    PATIENT_DETAILS_NOT_FOUND: "Set Patient Details.",
    DOCTOR_NOT_FOUND: "Doctor not found.",
    DOCTOR_DETAILS_NOT_FOUND: "Set Doctor Details.",
    ORGANIZATION_NOT_FOUND: "Organization NOT found",
    NO_APPOINTMENT_FOUND: "No appointment found.",
    USER_NAME_EXISTS: "Username already exists.",
    USER_EXIST: "Detail already exists.",
    EXERCISE_NOT_FOUND: "Exercise not found.",
    INCORRECT_OLD_PASSWORD: "Invalid old password.",
    ERROR_IN_UPDATING: "Error in updating.",
    FCM_TOKEN_NOT_FOUND: "FCM token not found. Unable to send notification.",
    PAYMENT_FAILED: "Payment verification failed",
    OTP_REQUIRED: "Otp is required.",
    EMAIL_REQUIRED: "Email is required.",
  },
  BANK_NAMES: {
    AUBL: "AU Small Finance Bank",
    AIRP: "Airtel Payments Bank",
    BARB_R: "Bank of Baroda - Retail Banking",
    VIJB: "Bank of Baroda - Retail Banking (Erstwhile Vijaya Bank)",
    MAHB: "Bank of Maharashtra",
    CNRB: "Canara Bank",
    CSBK: "Catholic Syrian Bank",
    CBIN: "Central Bank of India",
    DCBL: "DCB Bank",
    DEUT: "Deutsche Bank",
    DLXB: "Dhanlaxmi Bank",
    ESFB: "Equitas Small Finance Bank",
    FSFB: "Fincare Small Finance Bank",
    IBKL: "IDBI",
    IDFB: "IDFC FIRST Bank",
    IDIB: "Indian Bank",
    ALLA: "Indian Bank (Erstwhile Allahabad Bank)",
    IOBA: "Indian Overseas Bank",
    INDB: "Indusind Bank",
    JAKA: "Jammu and Kashmir Bank",
    JSFB: "Jana Small Finance Bank",
    KARB: "Karnataka Bank",
    KVBL: "Karur Vysya Bank",
    LAVB_R: "Lakshmi Vilas Bank - Retail Banking",
    NSPB: "NSDL Payments Bank",
    ORBC: "PNB (Erstwhile-Oriental Bank of Commerce)",
    UTBI: "PNB (Erstwhile-United Bank of India)",
    PSIB: "Punjab & Sind Bank",
    PUNB_R: "Punjab National Bank - Retail Banking",
    RATN: "RBL Bank",
    SVCB: "SVC Co-Operative Bank Ltd.",
    SRCB: "Saraswat Co-operative Bank",
    SIBL: "South Indian Bank",
    TMBL: "Tamilnad Mercantile Bank",
    UCBA: "UCO Bank",
    UJVN: "Ujjivan Small Finance Bank",
    UBIN: "Union Bank of India",
    CORP: "Union Bank of India (Erstwhile Corporation Bank)",
    YESB: "Yes Bank",
  },
  NOTIFICATION_ROUTES: {
    USER: "/user",
    ADMIN: "/admin",
    DELIVERY_AGENT: "/delivery-agent",
    CUSTOMER: "/customer",
    VENDOR: "/vendor",
    ALL: "/all",
  },
  ORDER_STATUS: {
    PENDING: "PENDING",
    ACCEPTED: "ACCEPTED",
    CANCELLED: "CANCELLED",
    OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
    DELIVERED: "DELIVERED",
    REJECTED: "REJECTED",
    RETURNED: "RETURNED",
    COMPLETED: "COMPLETED",
    SKIPPED: "SKIPPED",
    PROCESSING: "PROCESSING",
  },
};
